typedef enum {
	UNDEFINE, 
	UNAUTHENTICATE,
	AUTHENTICATED 
} STATE;

typedef enum {
	ERROR_USER = 30,
	ERROR_PASSWORD, 
	ERROR_STATE, 
	ERROR_LOGOUT,
	ERROR_LOGINED, 
	ERROR_FORM_MESSAGE, 
	ERROR_USER_BLOCKED 
} ERROR;

typedef enum {
	SUCCESS_USER = 40,
	SUCCESS_PASSWORD,
	SUCCESS_LOGOUT
} SUCCESS;